/*
 * File: app/view/LandingPage.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LandingPage', {
    extend: 'Ext.container.Viewport',

    style: '{background-color : gray}',
    autoScroll: true,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 0,
                    height: 640,
                    minHeight: 400,
                    minWidth: 400,
                    style: '{background-color : gray}',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    bodyBorder: false,
                    items: [
                        {
                            xtype: 'gridpanel',
                            border: 0,
                            height: 640,
                            id: 'pointsTable',
                            maxWidth: 640,
                            minHeight: 400,
                            minWidth: 400,
                            autoScroll: true,
                            title: 'IPL 2013 Points Table',
                            store: 'PointsTableStore',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var imgFilename="http://find-business.appspot.com/ipl/logos/"+value+".png";
                                        return "<img src=\""+imgFilename+"\" />";
                                    },
                                    width: 99,
                                    dataIndex: 'teamName',
                                    text: 'Logo'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 161,
                                    dataIndex: 'teamName',
                                    text: 'TeamName'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 52,
                                    dataIndex: 'matches',
                                    text: 'Matches'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 37,
                                    dataIndex: 'won',
                                    text: 'Won'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 41,
                                    dataIndex: 'lost',
                                    text: 'Lost'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 38,
                                    dataIndex: 'nr',
                                    text: 'Nr'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 51,
                                    dataIndex: 'netrr',
                                    text: 'Netrr'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 44,
                                    dataIndex: 'tied',
                                    text: 'Tied'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 44,
                                    dataIndex: 'points',
                                    text: 'Points'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    width: 53,
                                    dataIndex: 'forOver',
                                    text: 'ForOver'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'forRuns',
                                    text: 'ForRuns'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'againstOver',
                                    text: 'AgainstOver'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'againstRuns',
                                    text: 'AgainstRuns'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 57,
                                    dataIndex: 'chances',
                                    text: 'Chances'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            id: 'upcomingFixtures',
                            maxWidth: 360,
                            minHeight: 400,
                            minWidth: 360,
                            autoScroll: true,
                            title: 'Upcoming Fixtures',
                            store: 'FixturesTableStore',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var imgFilename="http://find-business.appspot.com/ipl/logos/"+value+".png";
                                        return "<img src=\""+imgFilename+"\" />";
                                    },
                                    width: 100,
                                    dataIndex: 'team1',
                                    text: 'Team1'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var imgFilename="http://find-business.appspot.com/ipl/logos/"+value+".png";
                                        return "<img src=\""+imgFilename+"\" />";
                                    },
                                    width: 100,
                                    dataIndex: 'team2',
                                    text: 'Team2'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 160,
                                    dataIndex: 'winner',
                                    emptyCellText: '<b>Double Click to Select</b>',
                                    text: 'Choose Winner',
                                    editor: {
                                        xtype: 'combobox',
                                        store: [
                                            
                                        ]
                                    }
                                }
                            ],
                            plugins: [
                                Ext.create('Ext.grid.plugin.CellEditing', {
                                    ptype: 'cellediting',
                                    listeners: {
                                        beforeedit: {
                                            fn: me.onGridcelleditingpluginBeforeEdit,
                                            scope: me
                                        }
                                    }
                                })
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            border: 0,
                            minHeight: 400,
                            style: '{background-color : gray}',
                            autoScroll: true,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Action',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 29,
                                    maxWidth: 1024,
                                    width: 269,
                                    text: 'Run Predictor',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 29,
                                    maxWidth: 1024,
                                    width: 269,
                                    text: 'Clear Predictions',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridcelleditingpluginBeforeEdit: function(editor, e, options) {
        var team1=e.record.get('team1');
        var team2=e.record.get('team2');
        e.column.getEditor().setValue("");
        e.column.getEditor().bindStore([team1,team2]);
    },

    onButtonClick: function(button, e, options) {
        var grid=Ext.ComponentQuery.query('#pointsTable')[0];
        var grid2=Ext.ComponentQuery.query('#upcomingFixtures')[0];
        var lineIndex=1;
        var formParamsIn="";
        Ext.each(grid2.getStore().data.items, function(item, index) {
            var line=item.get('team1')+','+item.get('team2')+','+item.get('winner');
            var param="param"+lineIndex+"="+line+"&";
            lineIndex=lineIndex+1;
            formParamsIn=formParamsIn+param;    
        });

        var store=Ext.create("MyApp.store.PointsTableStore",{autoLoad:false});
        store.setProxy({
            type: 'rest',
            api: {
                read: "http://find-business.appspot.com/ipl/predict"
            },
            actionMethods: {
                read: 'POST'
            },
            reader: {type:'json'},
            writer: {type:'json'}
        });
        store.on('load', function(v,r,success) {
            if(success) {        
                grid.getStore().loadRecords(r);
            }
        });
        store.load({params: formParamsIn});
    },

    onButtonClick1: function(button, e, options) {
        var grid=Ext.ComponentQuery.query('#pointsTable')[0];
        grid.getStore().load();
        var grid2=Ext.ComponentQuery.query('#upcomingFixtures')[0];
        grid2.getStore().setProxy({
            type: 'ajax',
            url: 'http://find-business.appspot.com/ipl/list?kind=Fixtures',
            reader: {
                type: 'json'
            }
        });
        grid2.getStore().load();
    }

});