/*
 * File: app/store/FixturesTableStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.FixturesTableStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.FixturesModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            storeId: 'MyJsonStore1',
            model: 'MyApp.model.FixturesModel',
            clearOnPageLoad: false,
            pageSize: 9,
            proxy: {
                type: 'ajax',
                url: 'http://find-business.appspot.com/ipl/list?kind=Fixtures',
                reader: {
                    type: 'json'
                }
            },
            listeners: {
                load: {
                    fn: me.onJsonstoreLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreLoad: function(store, records, successful, options) {
        store.setProxy({
            type: 'memory',
            reader: {
                type: 'json'
            }
        });
    }

});